version: 2

jobs:
  build:
    working_directory: /go/src/github.com/wearefair/k8-cross-cluster-controller
    docker:
      - image: golang:1.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-dir-{{ checksum "Gopkg.lock" }}
      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Install outdated deps
          command: dep ensure -v
      - run:
          name: Run unit tests
          environment:
            ENV: test
          command: |
            go test -v ./...
      - run:
          name: Verify the binary builds
          command: go build -v
