# Create this on both the local and remote side
# TODO: Once RBAC is in place, make the read-only an actually read-only controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cross-cluster-controller
  namespace: fair-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cross-cluster-controller-read-only
  namespace: fair-system
